groups:
    group1:
        worlds:
        - world1
        - world2
        shares:
        - inventory
        spawn:
          world: world1
        profiles:
        - default_profile
        - game_mode_profile
    group2:
        worlds:
        - world2
        - world3
        shares:
        - inventory
        - health
